### ISSUE TITLE
What should each post json look like?

### ISSUE THREAD

**Issue by nickbytes** [dumblr/dead#2]
So, we're going to generate a json file for each post. What should this look like?

Here's a really basic thought, give me more of your ideas

```
{
  "post": [
    {
      "id": "23lk4j2345lk345j2354kj3",
      "content": "something here",
      "timestamp": "11/17/06",
      "post_type": "text"
    }
  ]
}
```

**Comment by nickbytes** [comment]
Hmm wait no, whoops.

**Comment by nickbytes** [comment]
We probably don't need an array here...

**Comment by jayres** [comment]
Yeah, so my mock data is in the template file - and that seems to be sufficient for the time being. I was using UTC `Date() ` object for the timestamp object as a string. 

I think that we will probably come across other fields that need to be made when we actually start getting to display content more.

The biggest thing I am worried about is extending the markup (or markdown) in the actual JSON file. Do we want to do dangeroulyWriteHtml and sanitize before submitted and before reading?

I also was thinking about making the data schema more open and allowing additional fields to be included. TBH, when we finally share this with anyone and they use it - that's the last chance we get at a FULL data schema unless we can update on the fly using dat distribution (which I don't think we can unless we write an update function into the site).

**Comment by nickbytes** [comment]
>  I was using UTC Date() object for the timestamp object as a string.

Yea sorry, I just got lazy typing here lol.

And [this sample data](https://github.com/nickbytes/dumblr_2/blob/ui-building/dumblr_template/src/components/ContentView/index.js) look good. Nice.

**Comment by nickbytes** [comment]
> I also was thinking about making the data schema more open and allowing additional fields to be included.

This has me thinking of a possible 'plugin' architecture.

> TBH, when we finally share this with anyone and they use it - that's the last chance we get at a FULL data schema unless we can update on the fly using dat distribution (which I don't think we can unless we write an update function into the site).

Part of me kind of thinks its possible to do this by doing some sort of versioning + an update function. Maybe thats all just too much work though...

**Comment by nickbytes** [comment]
Wondering if [this](https://github.com/mapbox/remark-react) could help us get around some sanitization issues.

**Comment by nickbytes** [comment]
Also, I know we had some pretty cool ideas for extending post types... but what if we just didnt?

**Comment by jayres** [comment]
Here is an attempt. I think this should get us going pretty far. One major thought here is the text box might want to be an array of objects that indicate what the wrapping html tag is and then the textual content to prevent thousands of characters in a string for a larger text post.

```javascript
{
	"date": "", // UTC Date Object
	"type": "", // text/image/other types in the future
	"title": "", // post title
	"author": "", // handle of the user
	"author_address": "", // dat address of the user
	"author_avatar": "", //starting out with just emojis for simplicity but could be imgs
	"asset_ref": "", //reference to asset file in media folder
	"asset_description": "", // alt text or description for the image/asset
	"text_data": [
		{
			html_tag: "p",  //html wrapping tag for the item
			content: "",  // actual textual content
		},
	]
}
```

**Comment by jayres** [comment]
As a note to this: each head.json file should look like this:
```
{
	"user": "",
	"posts": [
		{
			"id": "", // Post ID - also the name of the json file in the subfolder
			"date": "" // Date for post verification on the query end
		},
                ... // All posts will be listed here as an object
	]
}
```

The purpose behind having the date object in the head is that when an external user query the posts, they will have to send the post ID and the date object to verify the post they are receiving. This is sort of security by obfuscation (which... is... as we know.... not the best) but should stop people from being able to spam users to discover `whisper` posts and also to verify posts across the network.
